#!/bin/bash
# Auto-generated by orchestrator - blocks file access outside project directory
# DO NOT EDIT - this file is overwritten on every execution
ALLOWED_DIR="/workspace/temp-orquestrador/users/5aaf347f-952f-4355-8513-ac3f4024b43e/projetos/suno"

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name')

deny() {
  local REASON="$1"
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"'"$REASON"'"}}'
  exit 0
}

check_path() {
  local RAW_PATH="$1"
  if [ -z "$RAW_PATH" ]; then return 0; fi
  local RESOLVED
  RESOLVED=$(realpath -m "$RAW_PATH" 2>/dev/null || echo "$RAW_PATH")
  if [[ "$RESOLVED" != "$ALLOWED_DIR"* && "$RESOLVED" != "/tmp"* && "$RESOLVED" != "/dev/null" && "$RESOLVED" != "/proc"* ]]; then
    deny "Acesso negado: $RESOLVED esta fora do diretorio do projeto. Voce so pode acessar arquivos dentro de $ALLOWED_DIR"
  fi
}

case "$TOOL_NAME" in
  Read|Write|Edit)
    check_path "$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')"
    ;;
  Glob)
    TARGET=$(echo "$INPUT" | jq -r '.tool_input.path // empty')
    if [ -n "$TARGET" ]; then check_path "$TARGET"; fi
    ;;
  Grep)
    TARGET=$(echo "$INPUT" | jq -r '.tool_input.path // empty')
    if [ -n "$TARGET" ]; then check_path "$TARGET"; fi
    ;;
  Bash)
    CWD=$(echo "$INPUT" | jq -r '.cwd // empty')
    if [ -n "$CWD" ] && [[ "$CWD" != "$ALLOWED_DIR"* ]]; then
      deny "Diretorio de trabalho $CWD esta fora do projeto $ALLOWED_DIR"
    fi
    CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty')
    CD_TARGET=$(echo "$CMD" | grep -oP '(?<=cd\s)/[^\s;&|"]+' | head -1)
    if [ -n "$CD_TARGET" ]; then check_path "$CD_TARGET"; fi
    CD_REL=$(echo "$CMD" | grep -oP '(?<=cd\s)\.\.[^\s;&|"]*' | head -1)
    if [ -n "$CD_REL" ] && [ -n "$CWD" ]; then
      check_path "$CWD/$CD_REL"
    fi
    for ABS_PATH in $(echo "$CMD" | grep -oP '(?:^|\s)/[a-zA-Z][^\s;&|"]*' || true); do
      RESOLVED=$(realpath -m "$ABS_PATH" 2>/dev/null || echo "$ABS_PATH")
      if [[ "$RESOLVED" != "$ALLOWED_DIR"* && "$RESOLVED" != "/tmp"* && "$RESOLVED" != "/dev"* && "$RESOLVED" != "/proc"* && "$RESOLVED" != "/usr"* && "$RESOLVED" != "/bin"* && "$RESOLVED" != "/etc"* && "$RESOLVED" != "/home"* ]]; then
        deny "Acesso negado: comando referencia $RESOLVED que esta fora de $ALLOWED_DIR"
      fi
    done
    ;;
esac

exit 0
